name: medical
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie:
  location: ^2.5.4
  flutter_sms:
  geocoding:
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  awesome_notifications: ^0.0.6+10
  email_validator: ^2.0.1




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    # توجد ثلاثه اوامر لنمفيذ المكتبة
    #flutter clean
    #flutter pub get
    #flutter pub run flutter_native_splash:create

  flutter_native_splash: ^0.2.8
flutter_native_splash:
    #backgroung color
  color: "#2582FA"
  image: "lib/assist/logo_ed.png"
  android: true
  ios: true
  android_gravity: center




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assist/
    - lib/lottie/

  fonts:
    - family: DroidKufi
      fonts:
        - asset: lib/assist/font/DroidKufi-Regular.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: lib/assist/font/Quicksand-Regular.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
